<a href="https://colab.research.google.com/github/anchalsinha-0411/Series-to-DataFrame/blob/main/series_to_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Data Frames

In [ ]:
import pandas as pd

In [ ]:
purchase_1=pd.Series({'Name':'Chris','Item Purchased':'Dog Food','Cost':22.50})
purchase_2=pd.Series({'Name':'Kevyn','Item Purchased':'Kitty Litter','Cost':2.50})
purchase_3=pd.Series({'Name':'Vinod','Item Purchased':'Bird Seed','Cost':5.00})

In [ ]:
df=pd.DataFrame([purchase_1,purchase_2,purchase_3],index=['Store 1','Store 1','Store 2'])
print(df)

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [ ]:
df #index of rows if for the dataframe and index columns for colors

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [ ]:
df2=df.to_csv('store.csv') #storing data frame in csv file

In [ ]:
df.loc["Store 2"]

Name                  Vinod
Item Purchased    Bird Seed
Cost                    5.0
Name: Store 2, dtype: object

In [ ]:
type(df.loc["Store 2"])()

Series([], dtype: object)

In [ ]:
df.describe()

            Cost
count   3.000000
mean   10.000000
std    10.897247
min     2.500000
25%     3.750000
50%     5.000000
75%    13.750000
max    22.500000

In [ ]:
df.shape

(3, 3)

In [ ]:
df.isnull()

          Name  Item Purchased   Cost
Store 1  False           False  False
Store 1  False           False  False
Store 2  False           False  False

In [ ]:
df.dtypes

Name               object
Item Purchased     object
Cost              float64
dtype: object

In [ ]:
df.count()

Name              3
Item Purchased    3
Cost              3
dtype: int64

In [ ]:
df['Name']

Store 1    Chris
Store 1    Kevyn
Store 2    Vinod
Name: Name, dtype: object

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df.loc["Store 1"]

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [ ]:
type(df.loc['Store 1'])

pandas.core.frame.DataFrame

In [ ]:
df.loc["Store 1",'Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [ ]:
df.T

                 Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5        5.0

In [ ]:
df.T.loc["Cost"]

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: object

In [ ]:
df.loc[:,["Name","Cost"]] #only appyling colon ':' refers all the rows

          Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [ ]:
df.drop("Store 1")

          Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

In [ ]:
df.drop("Store 2")

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [ ]:
df

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [ ]:
df1=df.copy()

In [ ]:
df1

          Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [ ]:
del df1["Name"]

In [ ]:
df1

        Item Purchased  Cost
Store 1       Dog Food  22.5
Store 1   Kitty Litter   2.5
Store 2      Bird Seed   5.0

In [ ]:
df["location"]='Asansol','Kolkata','Bihar' #adding new column into the dataframe

In [ ]:
df

          Name Item Purchased  Cost location
Store 1  Chris       Dog Food  26.5  Asansol
Store 1  Kevyn   Kitty Litter   6.5  Kolkata
Store 2  Vinod      Bird Seed   9.0    Bihar

In [ ]:
Costs=df['Cost']

In [ ]:
Costs+=2

In [ ]:
df

          Name Item Purchased  Cost location
Store 1  Chris       Dog Food  28.5  Asansol
Store 1  Kevyn   Kitty Litter   8.5  Kolkata
Store 2  Vinod      Bird Seed  11.0    Bihar

from matplotlib import pyplot as plt
df['Cost'].plot(kind='hist', bins=20, title='Cost')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Item Purchased').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('location').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Cost'].plot(kind='line', figsize=(8, 4), title='Cost')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Item Purchased'].value_counts()
    for x_label, grp in df.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('Item Purchased')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['location'].value_counts()
    for x_label, grp in df.groupby('Item Purchased')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Item Purchased')
_ = plt.ylabel('location')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Cost', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Item Purchased'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Cost', y='Item Purchased', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['location'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Cost', y='location', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.loc["Store 3"] = pd.Series({'Cost':12.5,'item Purchased':'Dog Food','Name':'Random','location':'None'})

In [ ]:
df.iloc[0:2,0:2]

          Name Item Purchased
Store 1  Chris       Dog Food
Store 1  Kevyn   Kitty Litter

In [ ]:
import pandas as pd
purchase_1=pd.Series({'Name':'Chris','Item Purchased':'Dog Food','Cost':22.50})

Questions

In [ ]:
#1

import pandas as pd
data_1=pd.Series({'Name':'Anuj Meheta','Tikets':5,'Amount':1355})
data_2=pd.Series({'Name':'Sandeep Oza','Tikets':2,'Amount':1169})
data_3=pd.Series({'Name':'Manvi Sharma','Tikets':6,'Amount':1988})

In [ ]:
df=pd.DataFrame([data_1,data_2,data_3],index=['T001','T002','T003'])
print(df)

              Name  Tikets  Amount
T001   Anuj Meheta       5    1355
T002   Sandeep Oza       2    1169
T003  Manvi Sharma       6    1988

In [ ]:
d1=pd.Series({'Material':'Wooden','Colour':"Maroon",'Price':25000})
d2=pd.Series({'Material':'Plywood','Colour':"Yellow",'Price':20000})
d3=pd.Series({'Material':'Plastic','Colour':"Red",'Price':1500})
d4=pd.Series({'Material':'Stainless Steel','Colour':"Silver",'Price':55000})
d5=pd.Series({'Material':'Wooden','Colour':"Light Blue",'Price':2500})
d6=pd.Series({'Material':'Aluminium','Colour':"Golden",'Price':65000})

In [ ]:
df=pd.DataFrame([d1,d2,d3,d4,d5,d6],index=['Sofa','Dining Table','Chair','Sofa','Chair','Dining Table'])
print(df)

                     Material      Colour  Price
Sofa                   Wooden      Maroon  25000
Dining Table          Plywood      Yellow  20000
Chair                 Plastic         Red   1500
Sofa          Stainless Steel      Silver  55000
Chair                  Wooden  Light Blue   2500
Dining Table        Aluminium      Golden  65000

In [ ]:
df

                     Material      Colour  Price
Sofa                   Wooden      Maroon  25000
Dining Table          Plywood      Yellow  20000
Chair                 Plastic         Red   1500
Sofa          Stainless Steel      Silver  55000
Chair                  Wooden  Light Blue   2500
Dining Table        Aluminium      Golden  65000

In [ ]:
#display the details of the chair and sofa
df.loc[['Sofa','Chair']]

              Material      Colour  Price
Sofa            Wooden      Maroon  25000
Sofa   Stainless Steel      Silver  55000
Chair          Plastic         Red   1500
Chair           Wooden  Light Blue   2500

In [ ]:
#display the furniture details which price is more than 25000
df[df['Price']>25000]

                     Material  Colour  Price
Sofa          Stainless Steel  Silver  55000
Dining Table        Aluminium  Golden  65000

In [ ]:
#display the furniture details price under 10000
df[df['Price']<10000]

      Material      Colour  Price
Chair  Plastic         Red   1500
Chair   Wooden  Light Blue   2500

In [ ]:
#Display alternative rows
df.iloc[::2]

      Material      Colour  Price
Sofa    Wooden      Maroon  25000
Chair  Plastic         Red   1500
Chair   Wooden  Light Blue   2500

In [ ]:
#creating a dataframe using the 2d dictionary to store the following records
import pandas as pd

data={
    'Activity1':{'Blue House':98,'Red House':87,'Green House':59,'Yellow House':78},
    'Activity2':{'Blue House':85,'Red House':76,'Green House':67,'Yellow House':99},
    'Activity3':{'Blue House':88,'Red House':80,'Green House':91,'Yellow House':55}
}

In [ ]:
df=pd.DataFrame(data)
print(df)

              Activity1  Activity2  Activity3
Blue House           98         85         88
Red House            87         76         80
Green House          59         67         91
Yellow House         78         99         55

In [ ]:
df

              Activity1  Activity2  Activity3
Blue House           98         85         88
Red House            87         76         80
Green House          59         67         91
Yellow House         78         99         55

In [ ]:
#create a dataframe using the following matrix by ndarray,assign row,and column labels like MS Excel.

import pandas as pd
import numpy as np

data=np.array([[98,56,87],
              [32,76,65],
              [55,99,88]])
df=pd.DataFrame(data,columns=['A','B','C'],index=['1','2','3'])

In [ ]:
print(df)

    A   B   C
1  98  56  87
2  32  76  65
3  55  99  88

In [ ]:
df

    A   B   C
1  98  56  87
2  32  76  65
3  55  99  88